"""The POSITIVE identifiability result: full support => recovery converges.

Everything so far characterised where recovery FAILS. That is only the converse
half. The claim we actually need is the forward direction:

    PROPOSITION. For trajectories generated by policy pi, the environment
    conditional p(o' | a, h) is identified from the trajectory distribution for
    every history h and action a with P_pi(h, a) > 0. For any (h, a) with
    P_pi(h, a) = 0 the trajectory distribution is invariant to that conditional,
    so it is not identified.

Positivity => identified. Zero support => unidentified. The gamma sweep measures
the second clause. This module demonstrates the FIRST: under a full-support
policy (gamma=0, every action taken from every reachable state), the recovered
conditionals should converge to the truth as the sample grows.

Paper II already contains this case implicitly -- its exhaustive uniform-action
rollouts are full support and it recovered emissions to TV <= 0.001 -- but it was
never framed as identifiability. Here we show the convergence explicitly.

WHAT WOULD FALSIFY IT: if the error PLATEAUS well above zero as N grows, then
full support is not sufficient in practice and something else binds (bond
dimension ceiling, optimiser bias, estimator inconsistency). We report the curve
either way, and we fit the decay to check it is consistent with a sqrt(N) rate
rather than a floor.

Run:  python -m src.paper3.identifiability
"""
from __future__ import annotations

import json
import pathlib
from collections import Counter

import numpy as np

from . import agents, persistent_tmaze as pt, phenotype as ph
from . import recovery_fidelity as rf
from .gamma_sweep import _spec_at
from .structure_phenotype import HISTORIES

CACHE = pathlib.Path(__file__).with_name("_identifiability.json")

N_VALUES = (200, 800, 3200, 6400)
EPOCHS = 40


def support_check(rollouts):
    """Verify the policy really is full support: every (state, action) exercised.
    The positive claim is conditional on this, so it must be checked, not assumed."""
    counts = Counter()
    for a, o in rollouts:
        counts[(int(a[1]), tuple(int(x) for x in o[1]), int(a[2]))] += 1
    total = missing = 0
    for name, a1, otup in HISTORIES:
        for a3 in range(4):
            total += 1
            if counts[(a1, otup, a3)] == 0:
                missing += 1
    return {"rows": total, "unexercised": missing, "full_support": missing == 0}


def measure(n_episodes: int, epochs: int = EPOCHS, seed: int = 0):
    spec = _spec_at(0.0)                     # gamma=0 => uniform policy, full support
    rollouts, _ = agents.rollout(spec, n_episodes, seed, verify=False)
    sup = support_check(rollouts)
    pool, _ = pt.rollouts_to_memory_pool(rollouts)
    mps, joint = ph.train_agent_mps(pool, epochs=epochs, seed=seed)
    tensors = [m.detach().cpu().numpy() for m in mps.matrices]
    fmap = rf.fidelity_map(tensors, joint)
    errs = [v["error"] for v in fmap.values() if np.isfinite(v["error"])]
    return {"n": n_episodes, "error": float(np.mean(errs)),
            "error_max": float(np.max(errs)), **sup}


def run(n_values=N_VALUES, epochs: int = EPOCHS, seeds=(0,)):
    """Repeat each N over several seeds. A single run per N cannot distinguish a
    genuine plateau from one unlucky optimisation trajectory -- the first pass at
    this showed a clean sqrt(N) decay for three points and then a doubling at the
    fourth, which is exactly the ambiguity repeats resolve."""
    rows = []
    for n in n_values:
        per_seed = [measure(n, epochs, s) for s in seeds]
        errs = [p["error"] for p in per_seed]
        r = {"n": n, "error": float(np.mean(errs)), "std": float(np.std(errs)),
             "runs": errs, "unexercised": max(p["unexercised"] for p in per_seed),
             "rows": per_seed[0]["rows"],
             "full_support": all(p["full_support"] for p in per_seed)}
        rows.append(r)
        print(f"  N={n:6d}  mean err={r['error']:.4f} +/- {r['std']:.4f}"
              f"  runs={[round(e,3) for e in errs]}", flush=True)
    CACHE.write_text(json.dumps(rows, indent=2))
    return rows


if __name__ == "__main__":
    print("Full-support policy (gamma=0). If identifiability holds, recovery error\n"
          "should DECAY toward zero with N, not plateau.\n")
    rows = run(seeds=(0, 1, 2))

    N = np.array([r["n"] for r in rows], float)
    E = np.array([r["error"] for r in rows], float)
    S = np.array([r["std"] for r in rows], float)
    print(f"\n{'N':>8s}{'mean err':>11s}{'std':>9s}{'ratio vs prev':>15s}")
    for i, r in enumerate(rows):
        ratio = "-" if i == 0 else f"{E[i]/E[i-1]:.2f}"
        print(f"{r['n']:8d}{r['error']:11.4f}{S[i]:9.4f}{ratio:>15s}")

    # log-log slope: a sqrt(N) statistical rate gives slope ~ -0.5; a floor gives ~0
    slope = float(np.polyfit(np.log(N), np.log(E), 1)[0])
    monotone = bool(np.all(np.diff(E) < 0))
    print(f"\nlog-log slope = {slope:+.3f}   (~-0.5 => statistical convergence;"
          " ~0 => a floor)")
    print(f"monotone decreasing: {monotone}")
    if not all(r["full_support"] for r in rows):
        print("WARNING: not every run had full support; the positive claim is"
              " conditional on it.")

    # a single non-monotone point must not be swamped by a favourable slope fit,
    # which is exactly how the first (n=1 per N) pass produced a false PASS
    if slope < -0.25 and monotone:
        print("\nPOSITIVE RESULT: under full support the recovered conditionals converge\n"
              "toward the truth as N grows, monotonically and at roughly the statistical\n"
              "rate. Identifiability holds in the forward direction, and the gamma sweep\n"
              "characterises exactly when it breaks.")
    elif slope < -0.25:
        print("\nPARTIAL: the trend decays at roughly the statistical rate but is NOT\n"
              "monotone across N. Consistent with optimiser variance rather than a floor,\n"
              "but not clean enough to assert convergence. Report with the error bars.")
    else:
        print("\nNEGATIVE: error does not decay like a consistent estimator. Full support\n"
              "is not sufficient in practice here -- something else binds (bond ceiling,\n"
              "optimiser bias). The positive half of the claim is NOT demonstrated.")
